# Generated by Django 5.0.3 on 2024-03-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_happy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_happy',
        ),
        migrations.AddField(
            model_name='user',
            name='has_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_applicant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_recruiter',
            field=models.BooleanField(default=False),
        ),
    ]
