# Generated by Django 5.0.3 on 2024-03-07 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('physical_address', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('Lagos', 'Lagos'), ('Abuja', 'Abuja'), ('Kogi', 'Kogi')], max_length=20)),
                ('country', models.CharField(choices=[('Nigeria', 'Nigeria')], max_length=20)),
                ('established_on', models.PositiveIntegerField()),
                ('employees_total', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
