# Generated by Django 5.0.3 on 2024-03-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Mining', 'Mining'), ('Health', 'Health')], max_length=20, null=True),
        ),
    ]
